In [1]:
import os
import pandas as pd
from preprocess import PreprocessAccel

pre_acc = PreprocessAccel(sampling_rate=50)

In [ ]:
root_path = r'D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets'
window_size = 3 # window size in second
overlap = 0.35

In [ ]:
root_path = r'D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets'
window_size = 3 # window size in second
overlap = 0.35

file_path = os.path.join(root_path, "hand", "walking.csv")
data = pd.read_csv(file_path)
walking = pre_acc.segment_and_flatten_magnitude(
    label='walking', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

file_path = os.path.join(root_path, "hand", "sitting_standing_transition.csv")
data = pd.read_csv(file_path)
sitting_standing = pre_acc.segment_and_flatten_magnitude(
    label='sitting_standing_transition', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

file_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets\hand\running.csv"
data = pd.read_csv(file_path)
running = pre_acc.segment_and_flatten_magnitude(
    label='running', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

file_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets\hand\descending_stairs.csv"
data = pd.read_csv(file_path)
desen_stairs = pre_acc.segment_and_flatten_magnitude(
    label='descending_stairs', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

file_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets\hand\climbing_stairs.csv"
data = pd.read_csv(file_path)
climb_stairs = pre_acc.segment_and_flatten_magnitude(
    label='climbing_stairs', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

merge_df = pd.concat([walking, sitting_standing, running, desen_stairs, climb_stairs])
merge_df['label'].value_counts()

In [ ]:
file_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets\pocket\walking.csv"
data = pd.read_csv(file_path)
walking = pre_acc.segment_and_flatten_magnitude(
    label='walking', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

file_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets\pocket\sitting_standing_transition.csv"
data = pd.read_csv(file_path)
sitting_standing = pre_acc.segment_and_flatten_magnitude(
    label='sitting_standing', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

file_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets\pocket\running.csv"
data = pd.read_csv(file_path)
running = pre_acc.segment_and_flatten_magnitude(
    label='running', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

file_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets\pocket\descending_stairs.csv"
data = pd.read_csv(file_path)
desen_stairs = pre_acc.segment_and_flatten_magnitude(
    label='descending_stairs', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

file_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets\pocket\climbing_stairs.csv"
data = pd.read_csv(file_path)
climb_stairs = pre_acc.segment_and_flatten_magnitude(
    label='climbing_stairs', magnitude_column_name='magnitude', 
    df=data, window_size_sec=window_size, overlap=overlap)

In [5]:
merge_df = pd.concat([merge_df, walking, sitting_standing, running, desen_stairs, climb_stairs])
merge_df['label'].value_counts()

label
walking              270
running              176
sitting_standing     157
climbing_stairs      139
descending_stairs    133
Name: count, dtype: int64

In [6]:
merge_df.shape

(875, 252)

In [8]:
merge_df.to_csv('cleaned_combine_all_class_with_label_no_fft.csv', index=False)

In [8]:
merge_df.head()

,start_time,label,x1,x2,x3,x4,x5,x6,x7,x8,...,x241,x242,x243,x244,x245,x246,x247,x248,x249,x250
0,29,walking,9.391768,9.095416,9.116803,9.038429,8.920207,9.119304,9.344565,9.368447,...,9.120713,9.209533,9.354902,9.285413,9.279229,9.356500,9.339347,9.163902,9.274815,9.371030
1,2791,walking,9.339839,9.334993,9.274880,9.153142,9.202418,9.314295,9.340177,9.350540,...,10.843081,9.170971,7.791438,6.965673,6.593102,7.274070,8.719662,8.712233,8.784947,7.975563
2,5603,walking,9.394136,9.231343,9.252686,9.257068,9.281385,9.294100,9.152972,9.336755,...,10.808816,10.393205,9.804173,9.059288,7.812298,7.749445,7.859224,8.034451,8.413953,9.333868
3,8420,walking,7.183794,7.151433,6.730669,6.369309,7.059695,7.495365,8.232169,8.581987,...,6.619653,7.446160,7.250531,10.119066,15.669209,15.674033,13.891112,12.759346,14.375291,14.512705
4,11241,walking,9.832197,10.361916,10.715456,10.929579,11.233561,11.865534,13.391049,14.774566,...,8.623207,7.681159,7.276771,7.860083,8.214317,7.785602,7.446644,7.064347,7.367401,7.866696

In [2]:
fft_df = pre_acc.compute_fft_on_flattened_data(merge_df)
fft_df.sample(10)

NameError: name 'merge_df' is not defined

In [11]:
fft_df.to_csv('cleaned_combine_all_class_with_label_applied_fft.csv', index=False)

In [1]:
import os
import pandas as pd
import re
from glob import glob
from preprocess import PreprocessAccel

pre_acc = PreprocessAccel(sampling_rate=50)

root_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\new_datasets_many_position"
# root_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\clean_datasets"
# magnitude_column_name = "filtered_magnitude"  # Adjust if needed
magnitude_column_name = "magnitude"  # raw magnitude
window_size = 2  # Window size in seconds
overlap = 0.5

# Function to extract label from filename
def extract_label(filename):
    match = re.match(r'([a-zA-Z]+)', filename)
    return match.group(1) if match else filename

# Process all CSV files in the directory and subdirectories
all_data = []
for dirpath, _, filenames in os.walk(root_path):
    for filename in filenames:
        if filename.endswith(".csv"):  # Process only CSV files
            file_path = os.path.join(dirpath, filename)
            label = extract_label(filename)

            data = pd.read_csv(file_path)
            processed_data = pre_acc.segment_and_flatten_magnitude(
                label=label, magnitude_column_name=None, 
                df=data, window_size_sec=window_size, overlap=overlap
            )
            all_data.append(processed_data)

# Combine all processed data
if all_data:
    merged_df = pd.concat(all_data, ignore_index=True)
    print("Merged DataFrame shape:", merged_df.shape)
else:
    print("No CSV files found.")

Merged DataFrame shape: (7121, 102)

In [2]:
merged_df['label'].value_counts()

label
sitting       1346
nothing       1327
running       1272
walking       1232
descending     977
climbing       967
Name: count, dtype: int64

In [3]:
# Find the minimum count of all labels
min_count = merged_df['label'].value_counts().min()

# Downsample each class to match the smallest class count
balanced_df = (
    merged_df.groupby('label', group_keys=False)
    .apply(lambda x: x.sample(n=min_count, random_state=42))  # Ensures reproducibility
)

# Display the new class distribution
balanced_df['label'].value_counts()

C:\Users\tanar\AppData\Local\Temp\ipykernel_16752\3646188502.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=min_count, random_state=42))  # Ensures reproducibility

label
climbing      967
descending    967
nothing       967
running       967
sitting       967
walking       967
Name: count, dtype: int64

In [4]:
balanced_df.sample(5)

,start_time,label,x1,x2,x3,x4,x5,x6,x7,x8,...,x91,x92,x93,x94,x95,x96,x97,x98,x99,x100
3031,51791,descending,21.633463,9.877034,9.093531,9.828922,9.865769,8.927116,9.230433,9.649793,...,8.970953,8.140061,7.178398,7.507523,8.836753,9.029330,8.718079,8.357763,7.977531,7.900690
3611,250107,running,14.106102,14.859966,14.329780,11.008588,6.486748,6.553060,7.287043,7.075281,...,14.271794,16.113302,14.363502,5.292296,6.913762,8.602999,8.334441,7.554025,8.188956,15.675130
5998,207424,descending,8.327262,8.896342,8.474214,7.457842,7.991677,9.890536,12.956882,16.222888,...,8.550696,8.610656,9.139716,9.461205,9.755788,10.036030,9.913723,9.801990,10.274342,10.271485
2484,187894,sitting,8.973010,8.973010,9.018171,9.018171,8.747983,8.357978,8.113803,7.742642,...,9.231441,9.272039,9.250000,9.360443,9.330482,9.534469,9.353748,9.401415,9.318267,9.143621
5491,171074,walking,11.611882,12.152247,13.785315,13.960154,13.191865,11.727975,11.190889,11.320464,...,12.033063,11.609806,12.137075,13.923250,14.386588,12.597464,11.225689,10.495509,10.169238,9.804815

In [8]:
root_path = r'D:\git_repository\dsp_project\ignore_dir\datasets\ready_to_train'
filename = f"TEST_ONLY_flattened_no_fft_raw_mag_win{str(window_size)}_lab{str(int(overlap*100))}.csv"
balanced_df.to_csv(os.path.join(root_path, filename), index=False)

print(filename)

TEST_ONLY_flattened_no_fft_raw_mag_win2_lab50.csv

In [7]:
fft_df = pre_acc.compute_fft_on_flattened_data(balanced_df, num_samples=balanced_df.shape[1]-2, remove_flatten=True)
fft_df.sample(10)

,start_time,label,x102,x103,x104,x105,x106,x107,x108,x109,...,x143,x144,x145,x146,x147,x148,x149,x150,x151,x152
1250,202208,descending,992.379611,18.020290,13.206829,59.150676,116.086484,37.005362,34.311814,101.738661,...,8.674632,13.639983,11.874083,15.616059,9.048487,16.599164,10.743836,7.454548,6.283855,7.146081
8,115290,climbing,982.100291,7.872498,22.146124,51.757311,78.134581,22.754207,8.812399,33.777945,...,3.552628,3.551686,1.899943,5.387777,4.469982,2.357773,1.728149,3.816157,5.098817,4.278393
391,80025,climbing,1004.712961,14.304660,19.349232,49.153592,80.479002,25.969712,25.585940,49.560824,...,1.010081,1.201937,4.080169,2.592497,0.521233,2.683257,1.667412,1.392227,0.452063,2.245381
1167,188057,descending,1028.528227,3.455808,7.739511,44.714810,15.356158,6.269499,16.001848,17.297588,...,0.588523,0.198257,0.377451,0.407801,0.126631,0.923207,0.701008,0.437540,0.555006,0.286907
2563,4486,nothing,981.050791,44.273986,46.912961,43.085632,29.931664,12.712773,6.069057,3.944068,...,8.565823,8.431489,4.782217,3.805535,5.667403,8.580084,10.953642,8.202536,10.362312,14.205421
2746,79914,nothing,986.206648,0.045893,0.158152,0.182915,0.674550,0.624829,0.523140,0.293973,...,0.090850,0.059108,0.113366,0.077802,0.052290,0.013127,0.042663,0.047786,0.015893,0.082671
5683,118465,walking,985.691604,17.139773,9.927495,41.521522,159.795893,17.362111,29.966039,52.058383,...,2.506838,3.694010,1.930869,2.940746,1.407574,3.079904,0.778065,5.677085,3.795883,0.068193
3080,195580,running,1093.277917,17.240744,21.625517,67.930318,73.503788,89.649970,296.056690,23.414680,...,8.652046,4.524252,8.419334,10.872497,2.920216,3.969628,1.964740,3.691991,6.588943,6.361969
4631,225083,sitting,985.157547,26.634233,25.903502,5.705964,16.935761,19.733279,13.116512,9.203542,...,1.961606,2.080300,2.193928,1.336472,0.987990,1.537902,2.124631,2.231676,1.903964,1.584252
4234,3344,sitting,926.035478,5.689113,10.007444,14.118756,7.412120,5.064577,11.020964,8.733420,...,0.901243,2.482915,1.982221,2.704608,1.730718,1.298533,0.501529,1.754871,0.888810,0.057274

In [8]:
root_path = r'D:\git_repository\dsp_project\ignore_dir\datasets\ready_to_train'
# _format = 'flattened_with_fft' 
# _format = 'combine_time_feq' 
_format = 'NO_FILTER' 
filename = f"{_format}_win{str(window_size)}_lab{str(int(overlap*100))}.csv"
fft_df.to_csv(os.path.join(root_path, filename), index=False)
filename

'NO_FILTER_win2_lab50.csv'