In [2]:
from preprocess_accel import PreprocessAccel

pre_acc = PreprocessAccel(sampling_rate=50)
file_path = r"D:\git_repository\dsp_project\ignore_dir\datasets\datasets\hand\walking_22-02-2025_10-59-31_Oil.csv"
data = pd.read_csv(file_path)

In [4]:
# for image
segmeted = pre_acc.segment_accelerometer_data(df=data, window_size_sec=5, overlap=0.5)
segmeted.head()

   start_time                                        window_data
0          29       time     x     y     z
0      29 -0.90  3...
1        2791       time     x     y     z
0    2791 -0.99  3...
2        5603        time     x     y     z
0     5603 -0.88 ...
3        8420        time     x     y      z
0     8420  3.08...
4       11241        time     x     y      z
0    11241 -1.50...

In [6]:
# for tabular
segmeted = pre_acc.segment_and_flatten_accelerometer_data(df=data, window_size_sec=5, overlap=0.5)
segmeted.head()

,start_time,x1,y1,z1,x2,y2,z2,x3,y3,z3,...,z247,x248,y248,z248,x249,y249,z249,x250,y250,z250
0,29,-0.90,3.37,8.72,-0.84,3.31,8.43,-0.85,3.44,8.40,...,8.68,-0.97,3.31,8.49,-0.85,3.21,8.66,-0.83,3.33,8.72
1,2791,-0.99,3.25,8.70,-0.84,3.17,8.74,-0.97,3.23,8.64,...,7.82,3.59,1.18,7.85,3.79,1.16,7.84,3.44,1.04,7.12
2,5603,-0.88,3.25,8.77,-1.04,3.19,8.60,-1.00,3.29,8.59,...,7.20,-0.32,3.16,7.38,-0.89,2.84,7.87,-1.25,2.69,8.85
3,8420,3.08,1.19,6.38,2.95,1.54,6.33,2.85,1.65,5.87,...,12.35,1.14,6.73,10.78,3.04,6.55,12.43,2.89,5.09,13.28
4,11241,-1.50,2.50,9.39,-2.06,2.51,9.84,-2.25,2.71,10.12,...,7.07,-0.40,2.11,6.73,0.11,2.76,6.83,1.60,3.32,6.95